e2e: adjust $VM_HOSTNAME for policy node config usage.
containers/nri-plugins pull request #378
Opened 2024-10-04 16:33 UTC by klihub

Take into account that $VM_HOSTNAME's like xyzzy-foobar-22.04 will propagate to the VM distro hostname as xyzzy-foobar-22.

2024-10-04 16:55 UTC, kad approved these changes
LGTM

2024-10-05 04:45 UTC, fmuyassarov approved these changes

2024-10-07 07:05 UTC, askervin commented on test/e2e/run.sh
> +    node="${node%.*}"
491 looks suspicious, as we're cutting again the suffix after the last dot, but we don't do that after line 497 yet both $node act as keys to the same map/dict/object.

2024-10-07 07:06 UTC, askervin requested changes
Marking to "Request changes" to prevent merging by accident.

2024-10-07 09:37 UTC, askervin approved these changes
LGTM

2024-10-07 09:37 UTC, merged