Remove cache file support
containers/nri-plugins pull request #50
Opened 2023-05-24 10:31 UTC by jukkar

As we can get the full state of the pod and container from runtime, no need to cache the data.
Containerd already has support for this. For cri-o, one needs a version that has commit f59c1f72a837c2235010813b8f361bb57c8c551b ("sandbox: Handle PodLinuxOverhead and PodLinuxResources CRI fields") in it.

2023-05-24 11:35 UTC, klihub commented on pkg/resmgr/cache/cache.go
> +func (cch *cache) SerializeAsJSON() ([]byte, error) {
nitpick: should/could we use `cache.Snapshot()` here directly ? It is already exported. Or rename it if we don't like the name anymore ?

Also, if we've now nuked all code paths that might externally lock the cache and then invoke (indirectly) `cache.Snapshot()` (via `cache.Save()`), then I think we should lock the cache now while we take the snapshot. The command line option is always present. When enabled this function can be triggered externally. And while taking the snapshot, we iterate over the container and pod maps.

2023-05-24 11:35 UTC, klihub commented on pkg/resmgr/flags.go
> +	flag.BoolVar(&opt.CacheOutputEnable, "cache-output-enable", false, "Support cache output via HTTP handler.")
nitpick: Could we find/use a more descriptive command line option name for this ? Maybe `--enable-cache-http-query`, but I'm not good with names, so this is just a vague attempt at a name.

2023-05-24 11:35 UTC, klihub commented on test/e2e/files/nri-resource-policy-balloons-deployment.yaml.in
> +            - --cache-output-enable
nitpick: same nitpick, this sort of sticks out as 'I can't guess what this enables'...

2023-05-24 11:35 UTC, klihub requested changes
LGTM. I have a few nitpicks and a locking-related comment.

2023-05-24 13:45 UTC, klihub reviewed
Looks go to me now. Maybe we'll need to sit on this for a while, at least until the first CRI-O release is done with the merged related fixes.

And maybe we'll need to add a version check to pkg/resmgr/nri.go:Configure() to give an error (and maybe refuse to start up) if the runtime+version indicates a cri-o without the fixes.

2023-05-25 07:37 UTC, jukkar commented
Fixed the format error. We can address the cri-o version check later after the cri-o release.

2023-05-26 10:31 UTC, jukkar commented
Removed the cache rm task from todo file.

2023-06-19 11:03 UTC, jukkar commented
Rebased to main. Changed option name used by e2e test to `--enable-test-apis` to sync it with the e2e testing option introduced in #60

2023-11-18 13:22 UTC, klihub commented
We'll revisit this later. Closing for now.

2023-11-18 13:22 UTC, closed without merging