policy: Add template policy
containers/nri-plugins pull request #7
Opened 2023-03-24 11:05 UTC by oxxenix

This is an example policy that can be used to develop a new policy with proper functionality.

2023-03-24 11:33 UTC, klihub commented on cmd/template/main.go
> +	_ "github.com/intel/nri-resmgr/cmd/template/policy"
These import paths need to be updated to refer to this `github.com/containers/nri-plugins` repo.

2023-03-24 11:39 UTC, jukkar requested changes
Generally lgtm, but please do search and replace all mentions of
nri-resmgr to nri-resource-policy in this PR.

2023-03-24 11:39 UTC, jukkar commented on cmd/template/Dockerfile
> +COPY --from=builder /go/builder/build/bin/nri-resmgr-template /bin/nri-resmgr-template
please change `resmgr` to `resource-policy` here and other places in this PR

2023-03-24 11:39 UTC, jukkar commented on cmd/template/fallback.cfg.sample
> +
There is now extra line at the end of the file, please remove it.

2023-03-24 11:39 UTC, jukkar commented on cmd/template/main.go
> +	_ "github.com/intel/nri-resmgr/cmd/template/policy"
The module location has changed, please change
`intel/nri-resmgr/`
to
`containers/nri-plugins`

2023-03-24 11:39 UTC, jukkar commented on cmd/template/nri-resmgr-template-deployment.yaml.in
> +apiVersion: v1
rename the file to `nri-resource-policy-template-deployment.yaml.in`

2023-03-24 11:39 UTC, jukkar commented on cmd/template/nri-resmgr-template-deployment.yaml.in
> +  name: nri-resmgr
rename all `nri-resmgr` to `nri-resource-policy` in this file

2023-03-24 11:39 UTC, jukkar commented on cmd/template/nri-resmgr-template-deployment.yaml.in
> +            - /etc/nri-resmgr/nri-resmgr.cfg
`nri-resmgr` directory is changed to `nri-resource-policy` and filename to `nri-resource-policy.cfg`

2023-03-24 13:55 UTC, klihub commented on cmd/template/policy/template-policy.go
> +	"github.com/intel/nri-resmgr/pkg/resmgr/events"
These import paths need to be updated to point to the new location.

2023-03-24 16:06 UTC, jukkar commented
> Everything is now updated. If correct, could you please squash commits when merging?

You can do it yourself. Just squash them together `git rebase -i HEAD~2` and then force push to this branch.

2023-03-24 16:09 UTC, jukkar commented on cmd/template/fallback.cfg.sample
> +  Debug: resource-manager,cache,policy,resource-control
There is something wrong with this file, github complains that "no newline at the of file", can you verify that there is a newline "\n" at the end.

2023-03-27 07:19 UTC, jukkar commented on cmd/template/fallback.cfg.sample
> +  Debug: resource-manager,cache,policy,resource-control
Probably that is related to your editor then. You can see the exact characters what the commit contains with this command:
```
git show HEAD~1 | od -A x -t x1z -v -c
```
The last character of the file should be \n in this case, and not an empty line (which means two \n).

2023-03-30 06:52 UTC, closed without merging